server:
  port: 8085
eureka:
  client:
    serviceUrl:
<<<<<<< HEAD
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

=======
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost
>>>>>>> 2babafd24013e70a61e6ca664d6ec673e8cdf180


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-catalogo-service
          uri: lb://ms-catalogo-service
          predicates:
            - Path=/category/**
<<<<<<< HEAD
          filters:
            - AuthFilter
        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/category/**
=======
>>>>>>> 2babafd24013e70a61e6ca664d6ec673e8cdf180
