server:
  port: 7070
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Nick-Saim-MJ/Feign-Server.git # ruta del repositorio git
          searchPaths: config-data
          default-label: Security
  security:
    user:
      name: root
      password: 123456